#include <iostream>
using namespace std;

#ifndef UTILITY_H
#define UTILITY_H


enum GameMode { GAME_MODE_NOT_SET = -1, TWO_PLAYERS_MANUAL, AI_HELPER_MODE, AI_OPPONENT_MODE };
enum AIMode {AI_MODE_NOT_SET = -1, AI_HINT, AI_AUTO};
enum ColorOrderMode {COLOR_ORDER_NOT_SET = -1, YOU_WHITE_FIRST, YOU_BLACK_FIRST, OPPONENT_WHITE_FIRST, OPPONENT_BLACK_FIRST};

enum PlayerTurn {TURN_NOT_DEFINED = -1, YOUR_TURN, OPPONENT_TURN};
enum PlayerColor {COLOR_NOT_DEFINED = -1, YOU_WHITE_COLOR, YOU_BLACK_COLOR};

enum GamePhrase {OPENING, MIDGAME, ENDGAME};

#endif // !UTILITY_H


